core/urls.py
from django.urls import path
from .views import HomeView, AboutView

core_patterns = ([
    path('', HomeView.as_view(), name='home'),
    path('about', AboutView.as_view(), name='about'),
], 'core')

ecopoints/urls.py
from django.urls import path
from .views import (EvaluatedRecyclingPointRequestList,
                    InactivesRecyclingPointListView, RecyclingPointCreateView,
                    RecyclingPointDetailView, RecyclingPointListView,
                    RecyclingPointMapView, status_ecopoint, RecyclingPointDeleteView, RecyclingPointUpdateView)

ecopoints_patterns = ([
    path('request/', RecyclingPointCreateView.as_view(), name='request'),
    path('points/', RecyclingPointListView.as_view(), name='points'),
    path('waiting/', InactivesRecyclingPointListView.as_view(), name='for_aprove'),
    path('ajax/change_recycling/', status_ecopoint,
         name='update_recycling_status'),
    path('history/', EvaluatedRecyclingPointRequestList.as_view(), name='history_request'),
    path('detail/<int:pk>/', RecyclingPointDetailView.as_view(), name='recycling_detail'),
    path('maps/', RecyclingPointMapView.as_view(), name='map_view'),
    path('delete/<int:pk>/', RecyclingPointDeleteView.as_view(), name='delete_request'),
    path('update/<int:pk>/', RecyclingPointUpdateView.as_view(), name='update_point'),
], 'ecopoints')

tallerdesoftware/urls.py
from django.contrib import admin
from django.urls import path, include
from core.urls import core_patterns
from registration.urls import registration_patterns
from ecopoints.urls import ecopoints_patterns

urlpatterns = [
    path('', include(core_patterns)),
    # Admin Path
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # Login Path
    path('accounts/', include(registration_patterns)),
    path('ecopoints/', include(ecopoints_patterns)),
    path('accounts/', include('django.contrib.auth.urls')),
]

ecopoints/models.py
from django.db import models
from registration.models import Country, City
from django.utils import timezone
from registration.models import Person, Municipality
from django.core.validators import RegexValidator
# Create your models here.


class RecyclingPoint(models.Model):
    
    """
    Almacena un nuevo punto de reciclaje, relacionado a :model:`registration.City` y :model:`registration.Country`.
    """
    
    real_id_point = models.CharField(
        max_length=12, unique=True, verbose_name='RUT de la Empresa', validators=[
            RegexValidator(
                regex='^\d{1,2}\.\d{3}\.\d{3}[-][0-9kK]{1}$',
                message='RUT Incorrecto',
            ),
        ])
    name_point = models.CharField(
        max_length=50, verbose_name='Nombre de la empresa')
    address_point = models.CharField(
        max_length=100, verbose_name='Dirección de la empresa')
    latitude_point = models.FloatField(verbose_name='Latitud', help_text='Ingrese los valores con puntos para separar decimales')
    longitude_point = models.FloatField(verbose_name='Longitud', help_text='Ingrese los valores con puntos para separar decimales')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True,
                                verbose_name='Región en que está situada la empresa')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True,
                             verbose_name='Comuna en que está situada la empresa')
    is_active = models.BooleanField(default=False, verbose_name='Punto activo')

    class Meta:
        verbose_name = 'Punto de reciclaje'
        verbose_name_plural = 'Puntos de reciclaje'


class RecyclingPointRequest(models.Model):
    
    """
    Almacena un registro de solicitud nuevo punto de reciclaje, relacionado a :model:`registration.Person`, :model:`registration.Municipality` y :model:`ecopoints.RecyclingPoint`.
    """
    
    request_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Fecha de solicitud')
    request_approbation_date = models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de aprobación')
    was_evaluated = models.BooleanField(default=False, verbose_name='Fue evaluado')
    was_approved = models.BooleanField(default=False, verbose_name='Fue aprobado')
    request_user = models.ForeignKey(
        Person, on_delete=models.SET_NULL, null=True)
    request_municipality = models.ForeignKey(
        Municipality, on_delete=models.SET_NULL, null=True)
    request_recyclingpoint = models.ForeignKey(
        RecyclingPoint, on_delete=models.CASCADE)

ecopoints/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import RecyclingPoint


class RecyclingPointForm(forms.ModelForm):
    class Meta:
        model = RecyclingPoint
        fields = ('real_id_point', 'name_point', 'address_point',
              'latitude_point', 'longitude_point')
    
    def clean_real_id_point(self):
        if RecyclingPoint.objects.filter(real_id_point=self.cleaned_data['real_id_point']).exists():
            raise forms.ValidationError("El rut ya se encuentra registrado")
        return self.cleaned_data['real_id_point']

    def clean_latitude_point(self):
        if self.cleaned_data['latitude_point'] > 90 or self.cleaned_data['latitude_point'] < -90:
            raise forms.ValidationError("La Latitud debe ser entre -90 y 90")
        return self.cleaned_data['latitude_point']
    
    def clean_longitude_point(self):
        if self.cleaned_data['longitude_point'] > 180 or self.cleaned_data['longitude_point'] < -180:
            raise forms.ValidationError("La Longitud debe ser entre -180 y 180")
        return self.cleaned_data['longitude_point']

ecopoints/views.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.db.models.expressions import OrderBy
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from registration.decorators import municipality_required, person_required
from registration.models import City, Municipality, Country

from .models import RecyclingPoint, RecyclingPointRequest
from .forms import RecyclingPointForm

# Create your views here.


@method_decorator([login_required, person_required], name='dispatch')
class RecyclingPointCreateView(CreateView):

    """
    Renderiza el template y formulario para creación de :model:`ecopoints.RecyclingPoint`.

    Requiere que el usuario esté logeado y sea persona.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPoint`.

    ``fields``
    Filtro de campos a mostrar en el formulario.

    ``success_url``
    URL de redirección si el formulario es valido y almacenado sin problemas.

    ***Template:*** 

    :template:`ecopoints/ecopoints_form.html`
    """

    form_class = RecyclingPointForm
    success_url = reverse_lazy('core:home')
    template_name = "ecopoints/ecopoints_form.html"

    def get_form(self, form_class=None):
        
        """
        Obtiene la instancia del formulario actual para cambiar el tipo de input para los campos de
        """

        if form_class is None:
            form_class = self.get_form_class()
        form_class.__dict__['base_fields']['latitude_point'].widget = (
            forms.TextInput())
        form_class.__dict__['base_fields']['longitude_point'].widget = (
            forms.TextInput())
        return form_class(**self.get_form_kwargs())

    def form_valid(self, form):
        
        """
        Si el formulario es valido, añade la Comuna y Ciudad del :model:`registration.Person` logeado, luego genera un registro de la acción realizada instanciando un objeto tipo :model:`ecopoints.RecyclingPointRequest`.
        """
        
        self.object = form.save(commit=False)
        self.object.country = self.request.user.person.country
        self.object.city = self.request.user.person.city
        self.object.save()
        recycling_request = RecyclingPointRequest()
        recycling_request.request_user_id = self.request.user.person.id
        recycling_request.request_municipality_id = Municipality.objects.get(
            city=self.request.user.person.city_id).id
        recycling_request.request_recyclingpoint_id = RecyclingPoint.objects.get(
            id=self.object.id).id
        recycling_request.save()
        return super().form_valid(form)


@method_decorator([login_required, municipality_required], name='dispatch')
class RecyclingPointListView(ListView):
    
    """
    Renderiza el template que contiene el listado de los objetos registrados :model:`ecopoints.RecyclingPoint` y los filtra para limitar que cada municipalidad solo visualize los que están en su comuna y que haya sido evaluado y aprobado.

    Requiere que el usuario esté logeado y sea municipalidad.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPoint`.

    ***Template:*** 

    :template:`ecopoints/ecopoints_approved_list.html`
    """
    
    model = RecyclingPoint
    template_name = "ecopoints/ecopoints_approved_list.html"

    def get_queryset(self):
        
        """
         Filtra el queryset de la clase para solo mostrar los objetos :model:`ecopoints.RecyclingPoint` que tengan asociada la comuna de la municipalidad logeada en la instancia y que esté evaluado y aprobado.
        """
        
        return RecyclingPoint.objects.filter(city=self.request.user.municipality.city, is_active=True)


@method_decorator([login_required, municipality_required], name='dispatch')
class InactivesRecyclingPointListView(ListView):
    
    """
    Renderiza el template que contiene el listado de los objetos registrados :model:`ecopoints.RecyclingPoint` y los filtra para limitar que cada municipalidad solo visualize los que están en su comuna y que no hayan sido evaluados aún.

    Requiere que el usuario esté logeado y sea municipalidad.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPoint`.

    ***Template:*** 

    :template:`ecopoints/ecopoints_list.html`
    """
    
    model = RecyclingPoint
    template_name = "ecopoints/ecopoints_list.html"

    def get_queryset(self):
        
        """
         Filtra el queryset de la clase para solo mostrar los objetos :model:`ecopoints.RecyclingPoint` que tengan asociada la comuna de la municipalidad logeada en la instancia y que no haya sido evaluado.
        """
        
        return RecyclingPoint.objects.filter(city=self.request.user.municipality.city, is_active=False, recyclingpointrequest__was_evaluated=False)


@method_decorator([login_required, municipality_required], name='dispatch')
class EvaluatedRecyclingPointRequestList(ListView):
    
    """
    Renderiza el template que contiene el listado de los objetos evaluados :model:`ecopoints.RecyclingPointRequest` y los filtra para limitar que cada municipalidad solo visualize los que están en su comuna, mostrando si fueron aprobados o rechazados.

    Requiere que el usuario esté logeado y sea municipalidad.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPointRequest`.

    ***Template:*** 

    :template:`ecopoints/history_ecopoints_list.html`
    """
    
    model = RecyclingPointRequest
    template_name = "ecopoints/history_ecopoints_list.html"

    def get_queryset(self):
        
        """
         Filtra el queryset de la clase para solo mostrar los objetos :model:`ecopoints.RecyclingPointRequest` que tengan asociada la comuna de la municipalidad logeada en la instancia y que haya sido evaluado.
        """
        
        return RecyclingPointRequest.objects.filter(request_municipality_id=self.request.user.municipality.id, was_evaluated=True)


def status_ecopoint(request):
    
    """
    Renderiza listado de :model:`ecopoints.RecyclingPoint` registrados  y los filtra para limitar que cada municipalidad solo visualize los que están en su comuna y que no hayan sido evaluados aún.

    Requiere que la solicitud sea GET y tipo AJAX.

    ***Context:***

    ``ecopoint_id``
    ID de :model:`ecopoints.RecyclingPoint` a instanciar y actualizar el estado.
    
    ``ecopoint``
    Instancia de :model:`ecopoints.RecyclingPoint` asociada al ``ecopoint_id``.
    
    ``request_ecopoint``
    Instancia de :model:`ecopoints.RecyclingPointRequest` asociada a ``ecopoint``.
    
    ``points``
    Obtiene un nuevo listado de :model:`ecopoints.RecyclingPoint` limitado por la comuna de la municipalidad y que aun no han sido evaluadas.

    ***Template:*** 

    :template:`ecopoints/response/ecopoints_list.html`
    """
    
    if request.method == 'GET' and request.is_ajax():
        ecopoint_id = request.GET.get('point_request_id')
        ecopoint = RecyclingPoint.objects.get(id=ecopoint_id)
        request_ecopoint = RecyclingPointRequest.objects.get(
            request_recyclingpoint_id=ecopoint_id)
        request_ecopoint.was_evaluated = True
        if request.GET.get('change_type') == 'approved':
            ecopoint.is_active = True
            request_ecopoint.was_approved = True
        elif request.GET.get('change_type') == 'declined':
            ecopoint.is_active = False
            request_ecopoint.was_approved = False
        else:
            raise Http404
        request_ecopoint.save()
        points = RecyclingPoint.objects.filter(city=request.user.municipality.city,
            is_active=False, recyclingpointrequest__was_evaluated=False)
        ecopoint.save()
        return render(request, 'ecopoints/response/ecopoints_list.html', {'recyclingpoint_list': points})
    else:
        raise Http404


@method_decorator([login_required, municipality_required], name='dispatch')
class RecyclingPointDetailView(DetailView):
    
    """
    Renderiza el template que contiene detalles de la instancia :model:`ecopoints.RecyclingPoint` solicitada.

    Requiere que el usuario esté logeado y sea municipalidad.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPoint`.

    ***Template:*** 

    :template:`ecopoints/detail_ecopoint_info.html`
    """
    
    model = RecyclingPoint
    template_name = "ecopoints/detail_ecopoint_info.html"


@method_decorator([login_required, person_required], name='dispatch')
class RecyclingPointMapView(ListView):
    
    """
    Renderiza el template del mapa que posiciona a todos los registros de :model:`ecopoints.RecyclingPoint`.

    Requiere que el usuario esté logeado y sea persona.

    ***Context:***

    ``model``
    Instancia de :model:`ecopoints.RecyclingPoint`.

    ***Template:*** 

    :template:`ecopoints/detail_ecopoint_info.html`
    """
    
    model = RecyclingPoint
    template_name = "ecopoints/ecopoints_map.html"

    def get_context_data(self, **kwargs):
        
        """
        Añade al diccionario del contexto, citys que contiene todos los objetos de :model:`registration.City` y countrys que contiene todos los objetos de :model:`registration.Country`
        """
        
        context = super().get_context_data(**kwargs)
        context["citys"] = City.objects.all()
        context["countrys"] = Country.objects.all()
        return context

@method_decorator([login_required, municipality_required], name='dispatch')

ecopoints/templates/ecopoints/delete_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Confirmación de eliminación de registro{% endblock %}
{% block content %}
<section id="banner">
    <h2>Eliminación de punto de reciclaje <br><u>{{recyclingpoint.name_point}}</u></h2>
</section>
<section id="main" class="container">
    <section class="box special">
        <form action="" method="post">
            {% csrf_token %}
            <p>¿Estás seguro que quieres borrar "{{recyclingpoint.name_point}}"?</p>
            <input type="submit" value="Sí, estoy seguro" />
            <a href="{% url 'ecopoints:points' %}" class="button">Cancelar</a>
        </form>
    </section>
</section>
{% endblock%}

ecopoints/templates/ecopoints/detail_ecopoint_info.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
Detalle {{recyclingpoint.name_point}}
{% endblock title %}
{% block content %}
<section id="banner">
    <h2>Información detallada del punto de reciclaje.</h2>
</section>
<section id="main" class="container">
    <section class="box special">
        <p><h2><u>{{recyclingpoint.name_point}}</u></h2></p>
        <p>RUT: {{recyclingpoint.real_id_point}}</p>
        <p>Dirección: {{recyclingpoint.address_point}}</p>
        <p>Comuna: {{recyclingpoint.city.name}}</p>
        <p>Región: {{recyclingpoint.country.name}}</p>
        <p>Activo: 
            
            {% if recyclingpoint.is_active %}
                Activo
            {% elif not recyclingpoint.is_active %}
                Inactivo
            {% endif %}
                
        </p>
        <a href="{% url 'ecopoints:history_request' %}" class="button">Volver</a>
    </section>
</section>
{% endblock content %}

ecopoints/templates/ecopoints/ecopoints_approved_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
Listado Puntos de reciclaje
{% endblock title %}
{% block content %}
<!-- Banner -->
<section id="banner">
    <h2>Puntos de reciclaje - {{request.user.municipality.country}} - {{request.user.municipality.city}}</h2>
</section>
<!-- Main -->
<section id="main" class="container">
    <section class="box special">
        <h2>Listado de puntos de reciclajes registrados en su comuna.</h2>
        <!-- Form -->
        {% if recyclingpoint_list %}
        <table>
            <thead>
                <td style="color: black">RUT</td>
                <td style="color: black">Nombre</td>
                <td style="color: black">Dirección</td>
                <td style="color: black">Comuna</td>
                <td style="color: black">Coordenadas</td>
                <td style="color: black" colspan="2">Acciones</td>
            </thead>
            <tbody id="bodytable">
                {% for r in recyclingpoint_list %}
                <tr>
                    <td style="color: black">
                        <a href="{% url 'ecopoints:recycling_detail' r.id %}">{{r.real_id_point}}</a>
                    </td>
                    <td style="color: black">{{r.name_point}}</td>
                    <td style="color: black">{{r.address_point}}</td>
                    <td style="color: black">{{r.city}}</td>
                    <td style="color: black">
                        <a target="_blank"
                            href="https://maps.google.com/?q={{r.latitude_point|floatformat:'.2d'}},{{r.longitude_point|floatformat:'.2d'}}">
                            {{r.latitude_point|floatformat:".2d"}},{{r.longitude_point|floatformat:".2d"}}
                        </a>
                    </td>
                    <td><a href="{% url 'ecopoints:update_point' r.id %}" class="button">Actualizar</a></td>
                    <td><a href="{% url 'ecopoints:delete_request' r.id %}" class="button">Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No hay ningun punto activo en su zona.</p>
        {% endif %}
    </section>
</section>
{% endblock content %}

ecopoints/templates/ecopoints/ecopoints_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
Solicitud nuevo punto de reciclaje
{% endblock title %}
{% block content %}
<!-- Banner -->
<section id="banner">
    <h2>Registro nuevo punto en {{request.user.person.country}} - {{request.user.person.city}}</h2>
</section>
<!-- Main -->
<section id="main" class="container">
    <section class="box special">
        <h2>Ingrese la información de la empresa</h2>
        <!-- Form -->
        <form method="post" id="personForm" data-cities-url="{% url 'registration:ajax_load_cities' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="fit">
        </form>
    </section>
</section>
<script src="{% static 'registration/js/load-cities.js' %} "></script>
{% endblock content %}

ecopoints/templates/ecopoints/ecopoints_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
En espera de aprobación
{% endblock title %}
{% block content %}
<!-- Banner -->
<section id="banner">
    <h2>Puntos de reciclaje - {{request.user.municipality.country}} - {{request.user.municipality.city}}</h2>
</section>
<!-- Main -->
<section id="main" class="container">
    <section class="box special">
        <h2>Listado de puntos de reciclajes en espera de revisión en su comuna.</h2>
        <!-- Form -->
        {% if recyclingpoint_list %}
        <table id="ecopointsForAprove" data-ecopoints-url="{% url 'ecopoints:update_recycling_status' %}">
            <thead>
                <td style="color: black">RUT</td>
                <td style="color: black">Nombre</td>
                <td style="color: black">Dirección</td>
                <td style="color: black">Comuna</td>
                <td style="color: black">Coordenadas</td>
                <td style="color: black">Acciones</td>

            </thead>
            <tbody id="bodytable">
                {% include 'ecopoints/response/ecopoints_list.html' %}
            </tbody>
        </table>
        {% else %}
        <p>No hay ningun punto en espera de revisión en su zona.</p>
        {% endif %}
    </section>
</section>
<script src="{% static 'ecopoints/js/status-change.js' %} "></script>
{% endblock content %}

ecopoints/templates/ecopoints/ecopoints_map.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
Mapa de los puntos
{% endblock title %}
{% load leaflet_tags %}
{% block content %}
<section id="banner">
    <h2>Mapa</h2>
</section>
<!-- Main -->
<section id="main" class="container">
    <section class="box special">
        <div class="select-container" style="padding-bottom: 15px;">
            <select name="citys" class="citys">
                {% for co in countrys %}
                <optgroup label="{{co.name}}">
                    {% for c in citys %}
                    {% if c.country_id == co.id and c.id == request.user.person.city.id %}
                    <option value="{{c.id}}" selected data-value-lon='{{c.longitude|floatformat:".2d"}}'
                        data-value-lat='{{c.latitude|floatformat:".2d"}}'>{{c.name}}</option>
                    {% elif c.country_id == co.id %}
                    <option value="{{c.id}}" data-value-lon='{{c.longitude|floatformat:".2d"}}'
                        data-value-lat='{{c.latitude|floatformat:".2d"}}'>{{c.name}}</option>
                    {% endif %}
                {% endfor %}
                </optgroup>
                {% endfor %}
            </select>
        </div>
        {% leaflet_map "map" callback="map_init" %}
        <br>
        <a href="{% url 'core:home' %}" class="button">Volver al inicio</a>
    </section>

</section>
{% leaflet_js %}
{% leaflet_css %}
<script type="text/javascript">
    function map_init(map, options) {
        /* start-ignore*/
        {% for r in recyclingpoint_list %}
        var lon = '{{ r.longitude_point|floatformat:".2d" }}';
        var lat = '{{ r.latitude_point|floatformat:".2d" }}';
        L.marker([lat, lon]).addTo(map).bindPopup("<b>{{r.name_point}}</b><br>{{r.address_point}}, {{r.city.name}}.");
        {% endfor %}
        map.setView(['{{ request.user.person.city.latitude|floatformat:".2d" }}', '{{ request.user.person.city.longitude|floatformat:".2d" }}'], 12);
        $('select[name=citys]').change(function () {
            var lon = $('option:selected').attr("data-value-lon");
            var lat = $('option:selected').attr("data-value-lat");
            map.setView([lat, lon], 12)
        });
    }
</script>
{% endblock content %}

ecopoints/templates/ecopoints/history_ecopoints_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
Historial
{% endblock title %}
{% block content %}
<!-- Banner -->
<section id="banner">
    <h2>Puntos de reciclaje - Aprobados y Rechazados</h2>
</section>
<!-- Main -->
<section id="main" class="container">
    <section class="box special">
        <h2>Historial de peticiones evaluadas.</h2>
        <!-- Form -->
        {% if recyclingpointrequest_list %}
        <table>
            <thead>
                <td style="color: black">Fecha de solicitud</td>
                <td style="color: black">Fecha de revision</td>
                <td style="color: black">Punto de reciclaje</td>
                <td style="color: black">Usuario</td>
                <td style="color: black">Estado</td>
            </thead>
            <tbody id="bodytable">
                {% for r in recyclingpointrequest_list %}
                <tr>
                    <td style="color: black">{{r.request_date}}</td>
                    <td style="color: black">{{r.request_approbation_date}}</td>
                    <td style="color: black"><a class="button" href="{% url 'ecopoints:recycling_detail' r.request_recyclingpoint_id %}"
                            data-number-point="">Ver</a></td>
                    <td style="color: black"><a class="button" href="{% url 'registration:detail_user' r.request_user_id %}">Ver</a>
                    </td>
                    <td style="color: black">

                        {% if r.was_approved %}
                        <span style="color: green">Aprobado</span>
                        {% elif not r.was_approved %}
                        <span style="color: red">Rechazado</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No hay ningun punto activo en su zona.</p>
        {% endif %}
    </section>
</section>
{% endblock content %}

ecopoints/templates/ecopoints/update_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Actualización de punto{% endblock %}
{% block content %}
<section id="banner">
    <h2>Actualización de punto de reciclaje <br><u>{{recyclingpoint.name_point}}</u></h2>
</section>
<section id="main" class="container">
    <section class="box special">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Actualizar" />
        </form>
    </section>
</section>
{% endblock%}